config/routes.rb
Rails.application.routes.draw do
  root to: 'images#index'
  devise_for :users

  resources :images, only: [:new, :create, :destroy]
end

app/models/image.rb
class Image < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  belongs_to :user
  mount_uploader :src, ImageUploader

  #one convenient method to pass jq_upload the necessary information
  def to_jq_upload
    {
      "name" => read_attribute(:src),
      "size" => src.size,
      "url" => src.url,
      "thumbnail_url" => src.thumb.url,
      "delete_url" => image_path(:id => id),
      "delete_type" => "DELETE"
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @images = current_user.images
    respond_to do |format|
      format.html
      format.json { render json: @images.map(&:to_jq_upload).to_json }
    end
  end

  def new
    @image = current_user.images.build
  end

  def create
    files = Array(params[:image][:src]).map do |src|
      current_user.images.create! src: src
    end
    render json: { files: files.map(&:to_jq_upload) }
  end

  def destroy
    @image = current_user.images.find(params[:id])
    @image.destroy
    render :json => true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.erb
<h1>Gallery for <%= current_user.email %></h1>

<hr />

<%= link_to 'Add more...', new_image_path %>

<hr />

<% @images.each do |image| %>
  <%= image_tag image.src.url %>
<% end %>

app/views/images/new.html.erb
<%= link_to "<- See the gallery", root_path %>

<hr />

<%= render 'jquery_file_upload/basic_plus_ui/upload' %>
<%= render 'jquery_file_upload/basic_plus_ui/download' %>

<%= render 'jquery_file_upload/basic_plus_ui/form', file: @image, as: :src %>

<%= javascript_include_tag 'jquery-file-upload/basic-plus-ui' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jquery File Upload example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span8"><%= yield %></div>
  </div>
</div>

</body>
</html>